FROM ubuntu:20.04 AS builder

ENV TZ=UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
  apt-get -y install --no-install-recommends git curl gcc libssl-dev pkg-config

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

SHELL ["/bin/bash", "-c"]

RUN source ~/.cargo/env && rustup update 1.84

RUN git clone https://github.com/openmina/openmina

WORKDIR /openmina
