name: 'Setup WebAssembly Build Environment'
description: 'Setup Rust with WASM target and wasm-bindgen-cli with Cargo.lock based caching'
inputs:
  toolchain:
    description: 'Rust toolchain version'
    required: false
    default: 'nightly'
  cache-prefix:
    description: 'Cache prefix key'
    required: false
    default: 'v0'
runs:
  using: 'composite'
  steps:
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ inputs.toolchain }}

    - name: Setup WASM toolchain using Makefile
      shell: bash
      run: |
        make setup-wasm

    - name: Generate Cargo.lock hash
      id: cargo-lock-hash
      shell: bash
      run: |
        if [ -f "Cargo.lock" ]; then
          echo "hash=${{ hashFiles('**/Cargo.lock') }}" >> $GITHUB_OUTPUT
        else
          echo "hash=no-cargo-lock" >> $GITHUB_OUTPUT
        fi

    - name: Setup Rust Cache (Cargo.lock based)
      uses: Swatinem/rust-cache@v2
      with:
        # Use Cargo.lock hash as the primary cache key
        key: ${{ inputs.cache-prefix }}-${{ inputs.toolchain }}-${{ steps.cargo-lock-hash.outputs.hash }}
        # Shared cache key for fallback
        shared-key: ${{ inputs.cache-prefix }}-${{ inputs.toolchain }}-shared
        # Save cache on develop and main branches
        save-if: ${{ github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main' }}
        # Cache these directories for WASM builds
        cache-directories: |
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git
          target/
        # Don't cache the entire target directory for PRs to save space
        cache-targets: ${{ github.event_name == 'pull_request' && 'false' || 'true' }}
