name: 'Setup Container Dependencies'
description: 'Install libssl3t64 in container for Mina binaries'
runs:
  using: 'composite'
  steps:
    - name: Install libssl3t64
      shell: bash
      run: |
        apt-get update && \
           apt-get install -y --no-install-recommends libssl3t64 curl && \
           apt-get clean && \
           rm -rf /var/lib/apt/lists/*
